---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: labopenshift2
  name: labopenshift2
  namespace: labopenshift2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: labopenshift2
---
